# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Simeon Lisovski"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = ""

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; Simeon Lisovski, {year}"
legalblurb = "All opinions expressed here are my own and do not necessarily represent those of any other agencies or groups."

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 7  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = ['SL_aboutme.css']
  custom_js  = []

[params]
  # Your details.
  name = "Simeon Lisovski"
  role = "Postdoctoral Researcher"
  organizations = [ { name = "Swiss Ornithological Insitute", url = "http://www.vogelwarte.ch" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "avatar.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  # email = "flip@example.org"
  email1 = "simeon.lisovski" # using cryptedmail
  email2 = "gmail" # using cryptedmail
  email3 = "com" # using cryptedmail
  address = "3054 Physics Building, University of California, Riverside, CA 92521, USA"
  office_hours = "Email for appointment"
  phone = "x26168"
  # skype = "echo123"
  # telegram = ""
  
logo = ""


[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
[blackfriday]
  hrefTargetBlank = false  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Permalinks
[permalinks]
  posts = "/post/:year-:month-:slug/"
  talks = "/talk/:year-:slug/"