# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Simeon Lisovski"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; Simeon Lisovski, {year}"
legalblurb = "All opinions expressed here are my own and do not necessarily represent those of any other agencies or groups."

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""


############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 7  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
  color_theme = "fliptheme"
  font = "flipfont"

  # Your details.
  name = "Simeon Lisovski"
  role = "Postdoctoral Researcher"
  organizations = [ { name = "Swiss Ornithological Insitute", url = "http://www.vogelwarte.ch" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "avatar.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  # email = "flip@example.org"
  email1 = "simeon.lisovski" # using cryptedmail
  email2 = "gmail" # using cryptedmail
  email3 = "com" # using cryptedmail
  address = "3054 Physics Building, University of California, Riverside, CA 92521, USA"
  office_hours = "Email for appointment"
  phone = "x26168"
  # skype = "echo123"
  # telegram = ""
  
logo = "logo.png"  
  
# Social/Academic Networking
#
# Icon pack "fa" includes the following social network icons:
#
#   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
#   youtube, instagram, soundcloud
#
#   For email icon, use "fa" icon pack, "envelope" icon, and
#   "mailto:your@email.com" as the link.
#
#   Full list: https://fortawesome.github.io/Font-Awesome/icons/
#
# Icon pack "ai" includes the following academic network icons:
#
#   google-scholar, arxiv, orcid, researchgate, mendeley
#
#   Full list: https://jpswalsh.github.io/academicons/
  


  [[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:simeon.lisovski@gmail.com"
  cv = true

  [[params.social]]
  icon = "github"
  icon_pack = "ai"
  link = "http://www.github.com/slisovski"
  cv = true

  [[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.ch/citations?user=3y8AwdsAAAAJ&hl=en&oi=ao"
  cv = true

  [[params.social]]
  icon = "orcid"
  icon_pack = "ai"
  link = "https://orcid.org/0000-0002-6399-0035"
  cv = true

  [[params.social]]
  icon = "twitter"
  icon_pack = "ai"
  link = "http://www.twitter.com/S_Lisovski"
  cv = true



[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Permalinks
[permalinks]
  posts = "/post/:year-:month-:slug/"
  talks = "/talk/:year-:slug/"